server:
  port: 8762
  
spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          uri: ${HOME}/Documents/projects/cloud-properties
          search-paths: common, local
            
      